//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtyMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public int Id { get; set; }
        public string Napravlenie { get; set; }
        public string Samolet { get; set; }
        public string Vremya_vyleta { get; set; }
        public string Vremya_pribytia { get; set; }
    }
}
